config/routes.rb
Milk::Application.routes.draw do

  get "home/index"

  root 'home#index'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  get 'client_portal' => 'client_portal#index'
  get "client_portal/company_description" => "client_portal#company_description", as: :company_description
  get "client_portal/about" => "client_portal#about", as: :about
  get "client_portal/primary_object" => "client_portal#primary_object", as: :primary_object
  get "client_portal/investment" => "client_portal#investment", as: :investment
  get "client_portal/riot_ritual" => "client_portal#riot_ritual", as: :riot_ritual



  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    client_portal_path
  end
  def after_sign_up_path_for(resource)
    client_portal_path
  end
end

app/controllers/client_portal_controller.rb
class ClientPortalController < ApplicationController
  before_action :authenticate_user! 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  clear_respond_to 
  respond_to :json
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :json
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/client_portal_helper.rb
module ClientPortalHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/client_portal/create.js.erb
window.location = "<%= client_portal_path %>"

app/views/client_portal/index.html.erb
<%= render 'layouts/header' %>
<h2 class="portal_h">Beatrice Brown</h2>
<div id="portal_div">
  <%= image_tag ("brown.png"),class:"about_img" %>
  <p>
    <strong>Beatrice Brown </strong>
    is an artist whose multidisciplinary practice involves music, film, performance and painting. Musically she has collaborated with numerous artists
    including post punk band Selfish Cunt, Warrior Charge (Tricky), Jeffrey Lee Pierce project (Iggy Pop, Nick Cave, Deborah Harry), performance art group Joan
    of Ass as well as Steve Stella New (Rich Kids, PIL, Iggy Pop, Pearl Harbour) with whom she released two albums ‘Beastiality’ and ‘Stars and Wronguns' under
    the name of Beastellabeast. She performs regularly with Deadcuts. Her paintings, performance, sound and video works explore themes surrounding esoteric
    sexuality, ritual, out of body experience and possession and have been shown at ICA, the Roundhouse, 1 Exhibition Road, Pure Evil Gallery and Millenium St
    Ives, The Cornish Bienalle, Flowers Gallery, Art14, The Library Club. Beatrice played Nancy in Alison Murray's street Cult movie 'Mouth to Mouth'- Winner
    best film Brooklyn Film Festival, during 2015 she will play the lead role in Tony Ukpo's feature film 'The 17 Voices of Eloise Carmicheal'.
  </p>
  <p class="links">
    <a class="info_link" href="http://beatricebrown.net/">Website</a>
    <a class="info_link" href="http://vimeo.com/channels/beatricebrown">Vimeo</a>
    <a class="info_link" href="http://thebeatriceverse.tumblr.com/">Tumblr</a>
    <a class="info_link" href="http://www.241-24-7.com/">241-24-7</a>
    <a class="info_link" href="https://soundcloud.com/mk47/deadcuts-feat-beatrice-brown-floods">SoundCloud</a>
    <a class="info_link" href="https://www.youtube.com/watch?v=Oj9Ti3HsJOA">YouTube</a>
  </p>
</div>
<h2 class="portal_h">Therese Steele</h2>
<div id="portal_div">
  <%= image_tag ("steele.png"),class:"about_img" %>
  <div>
    <div id="steele">

    </div>
    <p>
      <strong>Therese Steele</strong>
      is an artist working with performance and installation. She lived for several years in Beijing were she studied photography at The Beijing Film School.
      Therese has several academic degrees including Modern &amp; Classical Chinese and Politics from the infinite radical leftwing breeding ground of SOAS -
      School Of Oriental And African Studies - London as well as MA in Performance Design and Practice from Central Saint Martins. Her work has been shown at
      The Freud Museum, Artsadmin, Gallery8, Cochrane Theatre, Camden People’s theatre and Stockholm Fringe Festival.
    </p>
    <p>
      Therese collaborates with choreographer and artist Alice Tatge and their joint work deals with notions surrounding sexuality, body sovereignty and
      censorship. Their most recent large scale project, titled Dyad, developed during the riots in Istanbul 2013 is currently showing at Metamatic:Taf
      Athens.
    </p>
    <p class="links">
      <a class="info_link" href="http://www.dyad.org.uk">Dyad</a>
      <a class="info_link" href="http://dyad.org.uk/DYAD/PUBLICATION.html">Dyad Publication</a>
      <a class="info_link" href="http://www.freud.org.uk/events/75483/all-in-search-of-a-greater-hunger/">Freud</a>
      <a class="info_link"
      href="http://theartfoundation.metamatic.gr/EN/BLOG_/art-culture/2280/An_interview_with_Alice_Tatge_and_Therese_Steele_(TatgeSteele_The_Dyad_Project)/"
      >
      The Art Foundation
    </a>
  </p>
</div>
</div>

app/views/client_portal/index.js.erb
window.location = "<%= client_portal_path %>"

app/views/client_portal/investment.html.erb
<%= render 'layouts/header' %>
<h2 class="portal_h">Business Plan</h2>
<div id="portal_div">
  <p class="plan_title">
    Steele &amp; Brown Ltd.
    Business Plan
    2015 - 2016
  </p>
  <p class="directors-title">
    <strong>Company Directors</strong>
  </p>
  <div id="directors">
    <div id="steele">
      <p class="plan_p">
        Therese Steele <br>
        Grove House Flat 6 <br>
        Stamford Grove West <br>
        N16 6LL <br>
        London
      </p>
      <p>
        07545 289 65 <br>
        therese@steele.se <br>
        steeleandbrown.com
      </p>
    </div>
    <div id="brown">
      <p>
        Beatrice Brown <br>
        2 Old Silk Mill,<br>
        St Marys,<br>
        Chalford <br>
        GL6 8HP
      </p>
      <p>
        07878335956 <br>
        soulbowhole@gmail.com <br>
        steeleandbrown.com
      </p>
    </div>
  </div>



  <p>
    <strong>Business Description</strong>
  </p>
  <p>
    Steele&amp;Brown is an artist run curatorial and events management company that aims to present the new wave of contemporary and fine art in models that
    represent the shift of focus in the art world.
  </p>
  <p>
    We will raise income through sales, corporate sponsorship/investment, and public funding.
  </p>
  <p>
    Our company will be available for investment through the Enterprise Initiative Scheme (E.I.S.)
  </p>
  <p>
    in April 2015.
  </p>
  <p>
    <strong>Events Schedule</strong>
  </p>
  <p>
    <strong>2015 RIOTANDRITUAL</strong>
  </p>
  <p>
    RIOTANDRITUAL a 1/2 night event that incorporates fine art installation with live bands and performance art. It will open at the Institute of Contemporary
    Arts (I.C.A.) London June 20th 2015. We will tour the model to an arts festival at Hilles House, Gloucestershire, then to Los Angeles and New York over a
    period of four weeks. Through corporate sponsorship, tickets and merchandise sales we predict a profit of 10,000UKP per event.
  </p>
  <p>
    <strong>2016 PRIMARYOBJECT</strong>
  </p>
  <p>
    PRIMARYOBJECT a large group art show to open during Frieze Art Fair, London October 2016. PRIMARYOBJECT will run at an independent central location for the
    period of a month, during this time we will host ticketed evening live events, concerts, workshops and a talks programme running in conjunction with the
    static gallery show.
  </p>
  <p>
    <strong>How we run successful events:</strong>
  </p>
  <p>
    ● Research and Development: Online research project, ‘NOUS’. An inclusive online portal that will show contributions and research by leading academics,
    artists and writers that will generate income by selling advertising opportunities. This project will grow in scale and extent over 18 months. We will
    publish selected aspects of our research at the launch of PRIMARYOBJECT. This model has been executed to high success by Mouse magazine Italy
    (International) and <a href="http://www.theartistascurator.com">www.theartistascurator.com</a>.
  </p>
  <p>
    ● Fundraising - By employing a committed, professional fundraiser we endeavor to raise salaries/ production budgets and event funding through the
    multifarious funding bodies available.
  </p>
  <p>
    ● Investment - Through the E.I.S. we will seek to raise 200,000UKP of corporate investment in the first 12 months of trade. Steele&amp;Brown will always
    retain 70% of shares.
  </p>
  <p>
    ● Sponsorship - We have good contacts with corporate sponsors and hope to raise not only monetary funds but also alcohol and catering sponsorship from
    restaurants such as Hix London.
  </p>
  <p>
    ● Curatorial programme - Steele&amp;Brown will run an inclusive curatorial programme, that will incorporate both master and emergent artists. We will
    research and present new methods of curation and works sales ie. sales of video and performance works to international collections.
  </p>
  <p>
    ● Works production - Works production budgets will be raised through mostly public sector grants and funding. We are also in communication with Pangolin
    London.
  </p>
  <p>
    ● PR and Marketing - Steele&amp;Brown will place PR as a top priority. We are in communication with Sutton PR as our prospective public relations advisors.
  </p>
  <p>
    ● Location - RIOT&amp;RITUAL will be hosted at four existing gallery spaces globally. PRIMARYOBJECT will be hosted at a non established central location,
    that we will source through Location House.
  </p>
  <p>
    ● Event production -
  </p>
  <p>
    ● Sales (Art) - Steele&amp;Brown offer artists a 30/70% cut of sales favouring the artist. We do this because we want to re define artists rights within
    the industry. We intend to sell the works we represent to some of the most respected collections internationally. Prices of works will range from under
    100UKP to over 100,000UKP.
  </p>
  <p>
    ● Sales (Tickets) - Ticket sales should be 100%net profit.
  </p>
  <p>
    ● Sales (Books and Merchandise) - Each event will have catalogues and merchandise for sale at the locations and online.
  </p>
  <p>
    ● Sales (Advertising) - Steele&amp;Brown offer space for advertising within our events, catalogues, and within our online domains.
  </p>
  <p>
    ● Touring - RIOT&amp;RITUAL will tour to London, Gloucestershire, L.A. and New York. PRIMARYOBJECT will tour to ArtBasel Miami.
  </p>

</div>

app/views/client_portal/primary_object.html.erb
<%= render 'layouts/header' %>
<h2 class="portal_h">Primary Object</h2>
<div id="portal_div">
  <p>
    <strong>PRIMARYOBJECT is a large group show that will open in London 2016 and run for an entire month.</strong>
    <strong></strong>
  </p>
  <p>
    In essence the show will be based on two pretexts.
  </p>
  <p>
    <strong>The first pretext</strong>
    being the exploration of the abstract notion of the MOTHER, shown in all her horror, love, creation and deific force.
  </p>
  <p>
    We believe that the idea of the MOTHER is calling out to be discussed and redefined within the art world and we have been successful in confirming a range
    of established and emergent artists from all genders and disciplines who will contribute works to the show (see list below).
  </p>
  <p>
    PRIMARYOBJECT will present a live music and performance event programme that will run alongside the 2D, sculptural, and installation works therefore
    setting this show apart from traditional gallery experiences.
  </p>
  <p>
    <strong>The second pretext</strong>
    for the show is equally ambitious and radical and concerns redefining the gallery model as we currently know it.
  </p>
  <p>
    In a time so wholly engrossed in the technological revolution, engagement with social media and creation of avatars we are all participating in a unified
    global virtual culture.
  </p>
  <p>
    PRIMARYOBJECT will endeavour to translate this participation into a gallery setting by inviting current I.B.As (Internet Based Artists) to respond to the
    themes via the medium of the internet.
  </p>
  <p>
    This aspect of the show has already started in the form of an online research project which will grow and expand throughout the curatorial and production
    stages of PRIMARYOBJECT. This blog will include interviews with leading academics/philosophers/artists/curators such as<a href="http://www.theartistascurator.org/">Elena Filipovic</a> (When Exhibitions Become Form: On the History of the Artist as Curator)	<a href="http://www.kurator.org/research/magda-tyzlik-carver-project/">Magda Tyzlik Carver</a> (‘Towards An Aesthetic of Common/s: Beyond Participation and
    it’s Post’, New Criticals October 15 2014.) <a href="http://www.rca.ac.uk/more/staff/dr-nina-power/">Nina Power</a> (Philosopher, senior lecturer at RCA
    and author of One Dimensional Woman Zer0 2009) and Ed Fornieles amongst others.
  </p>
  <p>
    <strong>List of confirmed artists:</strong>
  </p>
  <p>
    <strong></strong>
  </p>
  <p>
    <a href="http://www.pangolinlondon.com/artists/abigail-fallis"><strong>Abigail Fallis</strong></a>
    <a href="http://en.wikipedia.org/wiki/Young_British_Artists">YBA</a>
    sculptor will present works from <a href="http://www.damienhirst.com/projects/2012/freedom-not-genius">Damien Hirsts’ MurderMe collection.</a>
  </p>
  <p>
    <a href="http://www.tara-sthill.com/"><strong>Tara St Hill</strong></a>
    is a well established London based fashion stylist who will show her own sculptural response.
  </p>
  <p>
    <a href="http://www.etiwade.com/projects/new-body-of-work-shown-in-new-york-and"><strong>Eti Wade</strong></a>
    : Artist and academic, (most recently shown at Garis and Hahn NY and The Jerwood Space Family Politics Exhibition London) will present works/talks tailor
    made for the show.
  </p>
  <p>
    <a href="http://tula.nu/"><strong>Tula</strong></a>
    : Berlin based Swedish band and lead singer Fanny Risberg (actress of<a href="http://www.dramaten.se/Repertoar/Nico---Sphinx-of-Ice1/">Nico Dramaten 2014</a> och	<a href="http://www.dn.se/sthlm/fanny-risberg-1/">Upp till Kamp Svt 2007</a> ) will perform original music for the show.
  </p>
  <p>
    <a href="http://www.dobedo.co.uk/contributor/naimakarlsson/"><strong>Naima Karlsson</strong></a>
    photographer (daughter of Neneh Cherry) will make 2D works for the show.
  </p>
  <p>
    <a href="http://www.taishani.com/"><strong>Tai Shani</strong></a>
    London based multidisciplinary artist whose installation is currently showing at <a href="http://mirrorcity.southbankcentre.co.uk/">The Hayward Gallery</a>
    .
  </p>
  <p>
    <a href="http://www.ralphbrown.co.uk/"><strong>The estate of Ralph Brown RA</strong></a>
    has committed his sculpture ‘Mother and Child’.
  </p>
  <p>
    <a href="http://www.lucybeech.com/"><strong>Lucy Beech</strong></a>
    <strong> (</strong>
    Bloomberg New Contemporaries 2014)<strong> </strong>British performance and video artist will premiere an exclusive video work.
  </p>
  <p>
    <a href="http://www.aeknown.com/"><strong>The AEs</strong></a>
    (Dario Vigorito and Martin Tomlinson) will present groundbreaking internet based live performance.
  </p>
  <p>
    <a href="http://beatricebrown.net/">Beatrice Brown</a>
    transdisciplinary artist, will make am interactive sculptural installation including video work and sound.
  </p>
  <p>
    <a href="http://dyad.org.uk/DYAD/Enter.html">Therese Steele</a>
    Swedish artist, will premiere her new film.
  </p>
  <p>
    <strong></strong>
  </p>
  <p>
    <strong>Artists currently in discussion;</strong>
  </p>
  <p>
    <a href="http://www.zabludowiczcollection.com/collection/artists/ed-fornieles"><strong>Ed Fornieles</strong></a>
    , who has recently had a large solo show at the <a href="http://chisenhale.org.uk/archive/exhibitions/index.php?id=141">Chisenhale Gallery</a> that
    discussed themes of the family while presenting live internet based interactive streaming.
  </p>
  <p>
    Experimental, avante garde, composer<a href="http://run-riot.com/articles/blogs/interview-artist-ebe-oke-talks-run-riot-about-his-work-and-transformation"><strong>Ebe Oke</strong></a>	<strong> and</strong> <a href="http://www.laurieanderson.com/"><strong>Laurie Anderson</strong></a> (legendary, NY based composer, performance artist, m.
    Lou Reed).
  </p>
  <p>
    <strong>The Estate of </strong>
    <a href="http://www.corinneday.co.uk/exhibitions.php?action=view_exhibition&amp;id=9"><strong>Corrine Day</strong></a>
    : Legendary fashion photographer who discovered Kate Moss, accredited with forming the controversial aesthetic termed as ‘Heroin chic’. This show will
    present her lesser- known documentary photography of personal moments between mother Tara St Hill and her child, Mia.
  </p>
  <p>
    We have more information available should you wish to receive it. We look forward to hearing from you.
  </p>
  <p>
    Yours sincerely,
  </p>
  <p>
    Therese Steele &amp; Beatrice Brown
  </p>
  <p>
    <a href="http://www.dyad.org.uk">http://www.dyad.org.uk</a>
  </p>
  <p>
    <a href="http://www.beatricebrown.net">www.beatricebrown.net</a>
  </p>
</div>

app/views/client_portal/riot_ritual.html.erb
<%= render 'layouts/header' %>
<div id="portal_div">
  <h2 class="portal_h">Riot & Ritual</h2>
  <p>
    Riot and Ritual is Steele&amp;Browns first production, through which our aim is three fold.
  </p>
  <p>
    1) To rediscover ancient, intuitive and collective modes of art making and present work that not only speak of its thematic concepts of trance, ritual and
    riot but that also enables audience/visitors/participants to experience it through their own bodies.
  </p>
  <p>
    2) To establish Steele &amp; Brown within the artist establishment as a successful artist curatorial partnership.
  </p>
  <p>
    3) To present a much needed new way of curating that puts the right of the artist as central.
  </p>
  <p>
    RIOT AND RITUAL will give precedence to artworks whose form of expression is without words, for this reason music, choreography and sonic exploration will
    play a central role. Steele &amp; Brown believe that placing live music inside an art exhibition will heighten the audio attentive ability of each visitor.
    Much detailed planning will be dedicated to the scenography of constructing the "stage" in a non traditional setting. A 24 hour timescale will enable the
    energy of the show to build and ebb, harkening back to the Warholian/Velvet Underground fusion of rock n roll and contemporary art.
  </p>
  <p>
    Through the online research project running parallel Steele &amp; Brown hope to further discussion about new gallery modes in a post participatory climate
    while generating interest and recognition for the artists involved. Investments will go toward the artists production budgets, primarily supporting
    generation of radical concepts within precise production values and installation.
  </p>
</div>

app/views/home/index.html.erb
<div id="video-background">
  <%= video_tag "milk.mp4",id:"main-video", autoplay: true, :controls => false %>
</div>

<div class="logo">
  STEELE &amp; BROWN
</div>


<div id="bg_layer">
  <div id="pg1"></div>
  <div id="pg2"></div>
  <div id="pg3"></div>

  <div id="video-div">
    <div id="client_portal" class="client_portal">
      <a id="portal_form_button">Client Portal</a>
    </div>
    <div id="modal">
      <div class=""><%= image_tag ('close.png'),id:"close"%></div>
      <div id="sign_in_form" class="form">
        <h1>Sign In</h1>
        <%= form_for(User.new, as: :user, url: session_path(:user), remote: true,
        :authenticity_token => true) do |f| %>
        <%= f.email_field :email,  :placeholder => "Email" %><br>
        <%= f.password_field :password, autocomplete: "off", :placeholder => "Password" %><br>
        <!-- <%= f.check_box :remember_me %> <%= f.label :remember_me %><br> -->
        <%= f.submit "Sign in", :class => 'sessions_button'  %>
        <% end %>
        <!-- <%= link_to "Sign up", new_registration_path(User), :class => 'sessions_button'%> -->
        <a id="sign_up" class="sessions_button other_session_button"> Sign Up</a>
      </div>

      <div id="sign_up_form" class="form">
        <h1>Sign Up</h1>
        <%= form_for(User.new, as: :user, url: registration_path(:user), remote: true,
        :authenticity_token => true) do |f| %>

        <%= f.email_field :email,  :placeholder => "Email" %><br>
        <%= f.password_field :password, autocomplete: "off", :placeholder => "Password" %><br>
        <%= f.password_field :password_confirmation, autocomplete: "off", :placeholder => "Password" %><br>
        <div><%= f.submit "Sign up", :class => 'sessions_button'  %></div>
        <% end %>
        <a id="sign_in" class="sessions_button other_session_button"> Sign In</a>
      </div>
    </div>

</div>

<% if user_signed_in? %>
  <script charset="utf-8">
    $('#portal_form_button').click(function(){
      window.location = "<%= client_portal_path %>"
    });
  </script>
  <% else %>
  <script charset="utf-8">
    $('#portal_form_button').click(function(){
      $('#modal').fadeToggle();
    });
  </script>
<% end %>

<script charset="utf-8">

$('#close').click(function(){
  $('#modal').fadeOut();
});
$('#sign_up').click(function(){
  $('#sign_in_form').hide();
  $('#sign_up_form').fadeIn();

});
$('#sign_in').click(function(){
  $('#sign_up_form').hide();
  $('#sign_in_form').fadeIn();

});
</script>

app/views/layouts/_header.html.erb
<div id="portal-logo">
<h2 class="portal-logo">Steele & Brown</h2>
</div>
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
    data-target="#navbarLinks">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
</div>
<div class="collapse navbar-collapse" id="navbarLinks">
  <ul class="nav navbar-nav">
    <li class="<%= 'active' if current_page?(client_portal_path) %>"><%= link_to "Bio", client_portal_path %></li>
    <li class="<%= 'active' if current_page?(primary_object_path) %>"><%= link_to "Primary Object", primary_object_path %></li>
    <li class="<%= 'active' if current_page?(investment_path) %>"><%= link_to "Investment Opportunity",investment_path %></li>
    <li class="<%= 'active' if current_page?(riot_ritual_path) %>"><%= link_to "Riot & Ritual", riot_ritual_path  %></li>
    <li><%= link_to "Sign Out".html_safe, destroy_user_session_path, method: "delete" %></li>
    <!-- <li><a href="#">Menu</a></li>
    <li><a href="#">Gallery</a></li>
    <li><a href="#">Contact</a></li> -->

  </ul>
</div>
</nav>
<script charset="utf-8">


$('#portal-logo').click(function(){
  window.location = "<%= root_path %>"
});
$("nav li").click(function () {
  $("nav li.active").removeClass("active"); //Remove any "active" class
  $("nav li", this).addClass("active"); //Add "active" class to selected tab

  // $(activeTab).show(); //Fade in the active content
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Steele&Brown</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    "application", media: "all", :data => {'skrollr-stylesheet' => ''}, "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= javascript_include_tag "skrollr" %>

<%= javascript_include_tag "skrollr.stylesheets.min" %>
<%= javascript_include_tag "placeholder.min" %>

<script type="text/javascript">
var s = skrollr.init();
Placeholdem( document.querySelectorAll( '[placeholder]' ) );
</script>

</body>
</html>